name: firebase
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8

  # Firebase Core and Authentication
  firebase_core: ^3.3.0
  firebase_auth: ^5.0.0

  # Web Support
  firebase_core_web: 
  firebase_auth_web:  
  google_sign_in:
  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.2
  google_maps_flutter_web: ^0.5.10
  
 
  # GetWidget UI Library
  getwidget: ^4.0.0

  # Icons
  cupertino_icons: ^1.0.8
  flutter_webrtc: ^0.11.6+hotfix.1

  cloud_firestore: ^5.2.1
  geocoding: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ 



# 473449169642-konmnbeuohghugrujlokar5k68l6cefa.apps.googleusercontent.com